### PR TITLE
add architecture detection

### PR DESCRIPTION
**Pull request by cobalt2727**
you can now cross one more item off the "enhancements" bit of your blog post!

### CODE REVIEW

**Comment by TomChantler** [comment]
This is great, thank you! I noticed that there are a couple of minor issues that we should fix before merging.

I think we should set `detected_arch` just before your case statement (and then use it in the case statement), like this:

```
detected_arch=`dpkg --print-architecture`
case $detected_arch in
    "arm64"|"amd64"|"i386"|"armhf") echo "Architecture = $detected_arch" ;; # Plex's download page has 4 architectures available
    *) echo -e "\e[31mYour architecture is not supported by Plex! \e[0m" && exit 1 ;; # need to stop the script early if the architecture detection line fails (i.e. a user running PowerPC or any OS other than Debian/Ubuntu)
esac
```
And then we can refer to that value without setting it as an environment variable, if we use two sets of quotes, like this:
```
url=`echo $rawjson | jq -r -c '.computer.Linux.releases | .[] | select(.url | contains("'$detected_arch'")) | select(.url | contains("debian")) | .url'`
```
Also, since I am using the `dpkg` command, my code assumes we are running on a debian-based distro, so we might as well check for `debian` in the path (we could enhance this later). 

The reason for this change is that when I ran it on my machine it didn't have a value for `detected_arch` and then it downloaded the `.rpm` version of Plex by mistake.

Would you be happy to make these two small changes before I merge the PR?

**Comment by cobalt2727** [comment]
...Oh, yeah, that was my original plan - I just forgot to re-add the part where $detected_arch gets assigned a value when reorganizing the PR. Thanks for the catch!

**Comment by TomChantler** [comment]
Thanks for doing this. I have updated the blog post at https://tomssl.com/update-plex-server-on-ubuntu-automatically/ accordingly.

**Comment by cobalt2727** [comment]
> If you want to download the very latest (beta) version of Plex, then you have to have bought a PlexPass and also be authenticated when you grab the json file containing the downloads. The way this is done is by passing in a header containing X-Plex-Token. And the way that is done in the script is by pasting the token in, right at the top of the file, like this:

You may want to rewrite this part too, since I changed the script to read the token from an environment variable in https://github.com/TomChantler/Update-Plex/pull/1/commits/7fd4eb1bd6cfa62494a70dbfb432ace8aed469a8

**Pull request merged**
